/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    orders: Order;
    'rfq-requests': RfqRequest;
    products: Product;
    categories: Category;
    'attribute-groups': AttributeGroup;
    attributes: Attribute;
    'attribute-options': AttributeOption;
    'filter-groups': FilterGroup;
    'filter-fields': FilterField;
    'filter-options': FilterOption;
    'filter-presets': FilterPreset;
    media: Media;
    documents: Document;
    'admin-change-log': AdminChangeLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'rfq-requests': RfqRequestsSelect<false> | RfqRequestsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'attribute-groups': AttributeGroupsSelect<false> | AttributeGroupsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    'attribute-options': AttributeOptionsSelect<false> | AttributeOptionsSelect<true>;
    'filter-groups': FilterGroupsSelect<false> | FilterGroupsSelect<true>;
    'filter-fields': FilterFieldsSelect<false> | FilterFieldsSelect<true>;
    'filter-options': FilterOptionsSelect<false> | FilterOptionsSelect<true>;
    'filter-presets': FilterPresetsSelect<false> | FilterPresetsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'admin-change-log': AdminChangeLogSelect<false> | AdminChangeLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'sales' | 'catalog_manager' | 'seo' | 'agent';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  type: 'physical' | 'legal' | 'quote';
  status:
    | 'new'
    | 'pending_payment'
    | 'awaiting_payment'
    | 'paid'
    | 'fulfilling'
    | 'shipped'
    | 'delivered'
    | 'cancelled'
    | 'expired';
  /**
   * Auto-filled from contact/company.
   */
  customerLabel?: string | null;
  items: {
    sku: string;
    name: string;
    slug?: string | null;
    quantity: number;
    price?: number | null;
    lineTotal?: number | null;
    product?: (number | null) | Product;
    id?: string | null;
  }[];
  totals?: {
    subtotal?: number | null;
    vat?: number | null;
    deliveryCost?: number | null;
    total?: number | null;
  };
  customer?: {
    fullName?: string | null;
    email?: string | null;
    phone?: string | null;
    companyName?: string | null;
    inn?: string | null;
    kpp?: string | null;
    ogrn?: string | null;
    legalAddress?: string | null;
  };
  delivery?: {
    method?: ('pickup' | 'cdek' | 'boxberry' | 'russian-post' | 'tc') | null;
    address?: string | null;
    city?: string | null;
    cost?: number | null;
    trackNumber?: string | null;
    shippedAt?: string | null;
  };
  payment?: {
    method?: ('card' | 'invoice') | null;
    providerStatus?: ('none' | 'pending' | 'succeeded' | 'canceled') | null;
    providerRef?: string | null;
    paidAt?: string | null;
    amount?: number | null;
  };
  /**
   * Filled for legal orders.
   */
  invoice?: {
    number?: string | null;
    issuedAt?: string | null;
    pdfUrl?: string | null;
    validUntil?: string | null;
  };
  sourcePage?: string | null;
  /**
   * Used for public order page /cart/order/[token]/.
   */
  publicToken?: string | null;
  internalComment?: string | null;
  /**
   * Auto-collected status history.
   */
  history?:
    | {
        at?: string | null;
        from?: string | null;
        to?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  qualityStatus?: ('needs_review' | 'technical_review' | 'content_review' | 'ready') | null;
  sku: string;
  slug: string;
  externalId?: string | null;
  title: string;
  h1?: string | null;
  shortDescription?: string | null;
  description?: string | null;
  productType?: ('pdu' | 'surge_filter' | 'monitoring_controller' | 'accessory') | null;
  primaryCategory?: (number | null) | Category;
  categories?: (number | Category)[] | null;
  price?: {
    amount?: number | null;
    currency?: string | null;
    status?: ('request' | 'published' | 'hidden') | null;
  };
  availabilityStatus?: ('request' | 'in_stock' | 'preorder' | 'unavailable') | null;
  technicalAttributes?:
    | {
        attribute: number | Attribute;
        option?: (number | null) | AttributeOption;
        valueText?: string | null;
        valueNumber?: number | null;
        confidence?: ('manual' | 'high' | 'medium' | 'low') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Direct product image URLs from the source. Used to check the product card, import media, and verify public rendering.
   */
  imageLinks?:
    | {
        role?: ('primary' | 'gallery' | 'diagram' | 'other') | null;
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Related Payload media records. Direct source URLs are listed above in the Image links block.
   */
  media?: (number | Media)[] | null;
  documents?: (number | Document)[] | null;
  relatedProducts?: (number | Product)[] | null;
  ctaMode?: ('rfq' | 'buy' | 'consult') | null;
  rfqEnabled?: boolean | null;
  sourceUrl?: string | null;
  sourceRawTitle?: string | null;
  sourceRawDescription?: string | null;
  lastImportedAt?: string | null;
  schemaProductEnabled?: boolean | null;
  schemaBrand?: string | null;
  schemaManufacturer?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  qualityStatus?: ('needs_review' | 'technical_review' | 'content_review' | 'ready') | null;
  title: string;
  slug: string;
  categoryType: 'catalog' | 'seo_filter' | 'use_case' | 'service' | 'hidden';
  parent?: (number | null) | Category;
  h1?: string | null;
  intro?: string | null;
  primaryFilters?: (number | FilterField)[] | null;
  featuredProducts?: (number | Product)[] | null;
  relatedCategories?: (number | Category)[] | null;
  bottomSeoText?: string | null;
  schemaItemListEnabled?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-fields".
 */
export interface FilterField {
  id: number;
  code: string;
  label: string;
  group?: (number | null) | FilterGroup;
  /**
   * The filter should reference a controlled attribute so an agent can change it safely.
   */
  attribute?: (number | null) | Attribute;
  fieldType?: ('single_select' | 'multi_select' | 'range' | 'boolean') | null;
  categories?: (number | Category)[] | null;
  isActive?: boolean | null;
  showCounters?: boolean | null;
  recalculateCounters?: boolean | null;
  allowMultiple?: boolean | null;
  indexableAllowed?: boolean | null;
  zeroResultsBehavior?: ('disable' | 'hide' | 'show') | null;
  sortOrder?: number | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups".
 */
export interface FilterGroup {
  id: number;
  code: string;
  label: string;
  isActive?: boolean | null;
  sortOrder?: number | null;
  categories?: (number | Category)[] | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  code: string;
  label: string;
  group?: (number | null) | AttributeGroup;
  valueType?: ('option' | 'multi_option' | 'number' | 'boolean' | 'text') | null;
  unit?: string | null;
  isFilterable?: boolean | null;
  isComparable?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups".
 */
export interface AttributeGroup {
  id: number;
  code: string;
  label: string;
  description?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-options".
 */
export interface AttributeOption {
  id: number;
  code: string;
  label: string;
  attribute: number | Attribute;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  indexableAllowed?: boolean | null;
  seoSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  externalUrl?: string | null;
  alt?: string | null;
  caption?: string | null;
  role?: ('product_primary' | 'product_gallery' | 'diagram' | 'drawing' | 'hero' | 'article') | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  source?: string | null;
  sortOrder?: number | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  externalUrl?: string | null;
  documentType?:
    | (
        | 'passport'
        | 'manual'
        | 'drawing'
        | 'diagram'
        | 'certificate'
        | 'declaration'
        | 'registry'
        | 'datasheet'
        | 'other'
      )
    | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  versionLabel?: string | null;
  proofRole?: string | null;
  downloadCtaLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-requests".
 */
export interface RfqRequest {
  id: number;
  status: 'new' | 'in_progress' | 'needs_clarification' | 'quote_preparing' | 'quoted' | 'won' | 'lost' | 'spam';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  assignedManager?: (number | null) | User;
  sourcePage?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  customerType?: ('company' | 'person' | 'integrator') | null;
  companyName?: string | null;
  inn?: string | null;
  contactName: string;
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  deadline?: string | null;
  /**
   * Legacy JSON with SKU, name, and quantity from the form.
   */
  items?: string | null;
  requestedItems?:
    | {
        sku?: string | null;
        name?: string | null;
        quantity?: string | null;
        product?: (number | null) | Product;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  technicalSpec?: string | null;
  /**
   * JSON with request source and technical metadata.
   */
  analytics?: string | null;
  internalComment?: string | null;
  nextActionAt?: string | null;
  quoteSentAt?: string | null;
  quoteNumber?: string | null;
  expectedBudget?: number | null;
  decisionStatus?: ('unknown' | 'evaluating' | 'waiting_quote' | 'approval' | 'won' | 'lost') | null;
  closeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options".
 */
export interface FilterOption {
  id: number;
  code: string;
  label: string;
  field: number | FilterField;
  attributeOption?: (number | null) | AttributeOption;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  seoSlug?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  indexableAllowed?: boolean | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-presets".
 */
export interface FilterPreset {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  slug: string;
  category: number | Category;
  h1?: string | null;
  intro?: string | null;
  conditions?:
    | {
        field: number | FilterField;
        options?: (number | FilterOption)[] | null;
        id?: string | null;
      }[]
    | null;
  relatedLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-change-log".
 */
export interface AdminChangeLog {
  id: number;
  actorType: 'user' | 'agent' | 'script' | 'integration';
  actorName?: string | null;
  targetCollection: string;
  targetId?: string | null;
  targetLabel: string;
  changeType: 'create' | 'update' | 'publish' | 'archive' | 'import';
  beforeSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  diffSummary?: string | null;
  reason?: string | null;
  approvalStatus?: ('not_required' | 'pending' | 'approved' | 'rejected') | null;
  approvedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'rfq-requests';
        value: number | RfqRequest;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'attribute-groups';
        value: number | AttributeGroup;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'attribute-options';
        value: number | AttributeOption;
      } | null)
    | ({
        relationTo: 'filter-groups';
        value: number | FilterGroup;
      } | null)
    | ({
        relationTo: 'filter-fields';
        value: number | FilterField;
      } | null)
    | ({
        relationTo: 'filter-options';
        value: number | FilterOption;
      } | null)
    | ({
        relationTo: 'filter-presets';
        value: number | FilterPreset;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'admin-change-log';
        value: number | AdminChangeLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  customerLabel?: T;
  items?:
    | T
    | {
        sku?: T;
        name?: T;
        slug?: T;
        quantity?: T;
        price?: T;
        lineTotal?: T;
        product?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        subtotal?: T;
        vat?: T;
        deliveryCost?: T;
        total?: T;
      };
  customer?:
    | T
    | {
        fullName?: T;
        email?: T;
        phone?: T;
        companyName?: T;
        inn?: T;
        kpp?: T;
        ogrn?: T;
        legalAddress?: T;
      };
  delivery?:
    | T
    | {
        method?: T;
        address?: T;
        city?: T;
        cost?: T;
        trackNumber?: T;
        shippedAt?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        providerStatus?: T;
        providerRef?: T;
        paidAt?: T;
        amount?: T;
      };
  invoice?:
    | T
    | {
        number?: T;
        issuedAt?: T;
        pdfUrl?: T;
        validUntil?: T;
      };
  sourcePage?: T;
  publicToken?: T;
  internalComment?: T;
  history?:
    | T
    | {
        at?: T;
        from?: T;
        to?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-requests_select".
 */
export interface RfqRequestsSelect<T extends boolean = true> {
  status?: T;
  priority?: T;
  assignedManager?: T;
  sourcePage?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  customerType?: T;
  companyName?: T;
  inn?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  city?: T;
  deadline?: T;
  items?: T;
  requestedItems?:
    | T
    | {
        sku?: T;
        name?: T;
        quantity?: T;
        product?: T;
        id?: T;
      };
  message?: T;
  technicalSpec?: T;
  analytics?: T;
  internalComment?: T;
  nextActionAt?: T;
  quoteSentAt?: T;
  quoteNumber?: T;
  expectedBudget?: T;
  decisionStatus?: T;
  closeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  status?: T;
  qualityStatus?: T;
  sku?: T;
  slug?: T;
  externalId?: T;
  title?: T;
  h1?: T;
  shortDescription?: T;
  description?: T;
  productType?: T;
  primaryCategory?: T;
  categories?: T;
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
        status?: T;
      };
  availabilityStatus?: T;
  technicalAttributes?:
    | T
    | {
        attribute?: T;
        option?: T;
        valueText?: T;
        valueNumber?: T;
        confidence?: T;
        id?: T;
      };
  imageLinks?:
    | T
    | {
        role?: T;
        url?: T;
        alt?: T;
        id?: T;
      };
  media?: T;
  documents?: T;
  relatedProducts?: T;
  ctaMode?: T;
  rfqEnabled?: T;
  sourceUrl?: T;
  sourceRawTitle?: T;
  sourceRawDescription?: T;
  lastImportedAt?: T;
  schemaProductEnabled?: T;
  schemaBrand?: T;
  schemaManufacturer?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  status?: T;
  qualityStatus?: T;
  title?: T;
  slug?: T;
  categoryType?: T;
  parent?: T;
  h1?: T;
  intro?: T;
  primaryFilters?: T;
  featuredProducts?: T;
  relatedCategories?: T;
  bottomSeoText?: T;
  schemaItemListEnabled?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups_select".
 */
export interface AttributeGroupsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  description?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  group?: T;
  valueType?: T;
  unit?: T;
  isFilterable?: T;
  isComparable?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-options_select".
 */
export interface AttributeOptionsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  attribute?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sortOrder?: T;
  isActive?: T;
  indexableAllowed?: T;
  seoSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups_select".
 */
export interface FilterGroupsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  isActive?: T;
  sortOrder?: T;
  categories?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-fields_select".
 */
export interface FilterFieldsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  group?: T;
  attribute?: T;
  fieldType?: T;
  categories?: T;
  isActive?: T;
  showCounters?: T;
  recalculateCounters?: T;
  allowMultiple?: T;
  indexableAllowed?: T;
  zeroResultsBehavior?: T;
  sortOrder?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options_select".
 */
export interface FilterOptionsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  field?: T;
  attributeOption?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  seoSlug?: T;
  sortOrder?: T;
  isActive?: T;
  indexableAllowed?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-presets_select".
 */
export interface FilterPresetsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  category?: T;
  h1?: T;
  intro?: T;
  conditions?:
    | T
    | {
        field?: T;
        options?: T;
        id?: T;
      };
  relatedLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  externalUrl?: T;
  alt?: T;
  caption?: T;
  role?: T;
  products?: T;
  categories?: T;
  source?: T;
  sortOrder?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  externalUrl?: T;
  documentType?: T;
  products?: T;
  categories?: T;
  versionLabel?: T;
  proofRole?: T;
  downloadCtaLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-change-log_select".
 */
export interface AdminChangeLogSelect<T extends boolean = true> {
  actorType?: T;
  actorName?: T;
  targetCollection?: T;
  targetId?: T;
  targetLabel?: T;
  changeType?: T;
  beforeSnapshot?: T;
  afterSnapshot?: T;
  diffSummary?: T;
  reason?: T;
  approvalStatus?: T;
  approvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}