/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    orders: Order;
    carts: Cart;
    'rfq-requests': RfqRequest;
    products: Product;
    categories: Category;
    'attribute-groups': AttributeGroup;
    attributes: Attribute;
    'attribute-options': AttributeOption;
    'filter-groups': FilterGroup;
    'filter-fields': FilterField;
    'filter-options': FilterOption;
    'filter-presets': FilterPreset;
    media: Media;
    documents: Document;
    'admin-change-log': AdminChangeLog;
    'shipping-calculations': ShippingCalculation;
    'shipping-logs': ShippingLog;
    'crm-sync-jobs': CrmSyncJob;
    'notification-jobs': NotificationJob;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'rfq-requests': RfqRequestsSelect<false> | RfqRequestsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'attribute-groups': AttributeGroupsSelect<false> | AttributeGroupsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    'attribute-options': AttributeOptionsSelect<false> | AttributeOptionsSelect<true>;
    'filter-groups': FilterGroupsSelect<false> | FilterGroupsSelect<true>;
    'filter-fields': FilterFieldsSelect<false> | FilterFieldsSelect<true>;
    'filter-options': FilterOptionsSelect<false> | FilterOptionsSelect<true>;
    'filter-presets': FilterPresetsSelect<false> | FilterPresetsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'admin-change-log': AdminChangeLogSelect<false> | AdminChangeLogSelect<true>;
    'shipping-calculations': ShippingCalculationsSelect<false> | ShippingCalculationsSelect<true>;
    'shipping-logs': ShippingLogsSelect<false> | ShippingLogsSelect<true>;
    'crm-sync-jobs': CrmSyncJobsSelect<false> | CrmSyncJobsSelect<true>;
    'notification-jobs': NotificationJobsSelect<false> | NotificationJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'apiship-settings': ApishipSetting;
    'crm-settings': CrmSetting;
    'notifications-settings': NotificationsSetting;
  };
  globalsSelect: {
    'apiship-settings': ApishipSettingsSelect<false> | ApishipSettingsSelect<true>;
    'crm-settings': CrmSettingsSelect<false> | CrmSettingsSelect<true>;
    'notifications-settings': NotificationsSettingsSelect<false> | NotificationsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'sales' | 'catalog_manager' | 'seo' | 'agent';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  type: 'physical' | 'legal' | 'quote';
  status:
    | 'new'
    | 'draft'
    | 'pending_payment'
    | 'awaiting_payment'
    | 'paid'
    | 'fulfilling'
    | 'shipped'
    | 'delivered'
    | 'cancelled'
    | 'expired'
    | 'completed'
    | 'returned';
  /**
   * Auto-filled from contact/company.
   */
  customerLabel?: string | null;
  items: {
    sku: string;
    name: string;
    slug?: string | null;
    quantity: number;
    price?: number | null;
    lineTotal?: number | null;
    product?: (number | null) | Product;
    id?: string | null;
  }[];
  totals?: {
    subtotal?: number | null;
    vat?: number | null;
    deliveryCost?: number | null;
    total?: number | null;
  };
  customer?: {
    fullName?: string | null;
    email?: string | null;
    phone?: string | null;
    companyName?: string | null;
    inn?: string | null;
    kpp?: string | null;
    ogrn?: string | null;
    legalAddress?: string | null;
    /**
     * Flipped false after 3 hard bounces (049, edge case).
     */
    emailValid?: boolean | null;
  };
  delivery?: {
    method?: ('pickup' | 'cdek' | 'boxberry' | 'russian-post' | 'tc') | null;
    address?: string | null;
    city?: string | null;
    cost?: number | null;
    trackNumber?: string | null;
    shippedAt?: string | null;
    provider?: ('apiship' | 'fallback') | null;
    providerKey?: string | null;
    tariffId?: number | null;
    deliveryType?: ('1' | '2') | null;
    pickupType?: ('1' | '2') | null;
    pointId?: string | null;
    pointAddress?: string | null;
    etaMinDays?: number | null;
    etaMaxDays?: number | null;
    selectedAt?: string | null;
    addressNormalized?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Captured on Review step.
     */
    priceSnapshot?: {
      cost?: number | null;
      currency?: string | null;
      capturedAt?: string | null;
      sourceCacheKey?: string | null;
      refreshCheckAt?: string | null;
    };
    pickupExpiresAt?: string | null;
  };
  /**
   * Filled after ApiShip order creation.
   */
  shipment?: {
    providerOrderId?: string | null;
    trackingNumber?: string | null;
    trackingUrl?: string | null;
    labelUrl?: string | null;
    waybillUrl?: string | null;
    status?:
      | (
          | 'none'
          | 'pending'
          | 'created'
          | 'pending_label'
          | 'in_transit'
          | 'at_point'
          | 'delivered'
          | 'returned'
          | 'cancelled'
          | 'error'
        )
      | null;
    events?:
      | {
          eventId: string;
          providerStatus?: string | null;
          internalStatus?: string | null;
          at: string;
          receivedAt?: string | null;
          message?: string | null;
          raw?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[]
      | null;
    createdAt?: string | null;
    cancelledAt?: string | null;
    errorMessage?: string | null;
    lastSyncedAt?: string | null;
  };
  /**
   * Filled by 048-twenty-crm-sync.
   */
  crmRefs?: {
    opportunityId?: string | null;
    personId?: string | null;
    companyId?: string | null;
    lastSyncedAt?: string | null;
    lastSyncStatus?: ('queued' | 'in_progress' | 'success' | 'failed' | 'quarantined') | null;
    lastSyncError?: string | null;
    pendingCancellationFromCrm?: boolean | null;
  };
  deliveredAt?: string | null;
  closedAt?: string | null;
  /**
   * Derived: true iff active Return exists. Synced from returns.afterChange (053).
   */
  disputeFlag?: boolean | null;
  paymentRetryUntil?: string | null;
  /**
   * Computed from returns collection.
   */
  hasReturns?: boolean | null;
  returnsCount?: number | null;
  /**
   * In kopecks. Computed from returns.
   */
  totalRefunded?: number | null;
  payment?: {
    method?: ('card' | 'invoice') | null;
    providerStatus?: ('none' | 'pending' | 'succeeded' | 'canceled') | null;
    providerRef?: string | null;
    paidAt?: string | null;
    amount?: number | null;
    /**
     * Auto-filled on refund (053).
     */
    refunds?:
      | {
          providerRefundId: string;
          returnId?: string | null;
          /**
           * In kopecks.
           */
          amount: number;
          refundedAt: string;
          providerStatus?: ('pending' | 'succeeded' | 'failed') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Filled for legal orders.
   */
  invoice?: {
    number?: string | null;
    issuedAt?: string | null;
    pdfUrl?: string | null;
    validUntil?: string | null;
  };
  sourcePage?: string | null;
  /**
   * Used for public order page /cart/order/[token]/.
   */
  publicToken?: string | null;
  /**
   * Source cart for funnel analytics. Unique. May be empty for legacy orders.
   */
  cartId?: (number | null) | Cart;
  /**
   * Format SO-YYYY-NNNN. Auto-generated via PG SEQUENCE (051, FR-5101).
   */
  clientNumber?: string | null;
  /**
   * Filled when reissuing number via admin route. ≥10 chars.
   */
  clientNumberReissueReason?: string | null;
  clientNumberHistory?:
    | {
        oldNumber: string;
        reissuedAt: string;
        reason?: string | null;
        actorEmail?: string | null;
        id?: string | null;
      }[]
    | null;
  internalComment?: string | null;
  /**
   * Auto-collected status history.
   */
  history?:
    | {
        at?: string | null;
        from?: string | null;
        to?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Controlled via /preferences/[token]/.
   */
  marketingOptIn?: boolean | null;
  /**
   * Messenger consent placeholder for spec 050 (Telegram).
   */
  messengerOptIn?: boolean | null;
  /**
   * Mirror of notification-jobs for quick lookup.
   */
  notifications?:
    | {
        notificationId: string;
        event: string;
        channel: 'email' | 'messenger' | 'crm' | 'admin_ui' | 'dataLayer';
        template?: string | null;
        recipient?: string | null;
        scheduledAt?: string | null;
        sentAt?: string | null;
        status: 'queued' | 'sent' | 'failed' | 'skipped';
        errorMessage?: string | null;
        externalRef?: string | null;
        skipReason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  qualityStatus?: ('needs_review' | 'technical_review' | 'content_review' | 'ready') | null;
  sku: string;
  slug: string;
  externalId?: string | null;
  title: string;
  h1?: string | null;
  shortDescription?: string | null;
  description?: string | null;
  productType?: ('pdu' | 'surge_filter' | 'monitoring_controller' | 'accessory') | null;
  primaryCategory?: (number | null) | Category;
  categories?: (number | Category)[] | null;
  price?: {
    amount?: number | null;
    currency?: string | null;
    status?: ('request' | 'published' | 'hidden') | null;
  };
  availabilityStatus?: ('request' | 'in_stock' | 'preorder' | 'unavailable') | null;
  technicalAttributes?:
    | {
        attribute: number | Attribute;
        option?: (number | null) | AttributeOption;
        valueText?: string | null;
        valueNumber?: number | null;
        confidence?: ('manual' | 'high' | 'medium' | 'low') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Direct product image URLs from the source. Used to check the product card, import media, and verify public rendering.
   */
  imageLinks?:
    | {
        role?: ('primary' | 'gallery' | 'diagram' | 'other') | null;
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Related Payload media records. Direct source URLs are listed above in the Image links block.
   */
  media?: (number | Media)[] | null;
  documents?: (number | Document)[] | null;
  relatedProducts?: (number | Product)[] | null;
  ctaMode?: ('rfq' | 'buy' | 'consult') | null;
  rfqEnabled?: boolean | null;
  sourceUrl?: string | null;
  sourceRawTitle?: string | null;
  sourceRawDescription?: string | null;
  lastImportedAt?: string | null;
  schemaProductEnabled?: boolean | null;
  schemaBrand?: string | null;
  schemaManufacturer?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  qualityStatus?: ('needs_review' | 'technical_review' | 'content_review' | 'ready') | null;
  title: string;
  slug: string;
  categoryType: 'catalog' | 'seo_filter' | 'use_case' | 'service' | 'hidden';
  parent?: (number | null) | Category;
  h1?: string | null;
  intro?: string | null;
  primaryFilters?: (number | FilterField)[] | null;
  featuredProducts?: (number | Product)[] | null;
  relatedCategories?: (number | Category)[] | null;
  bottomSeoText?: string | null;
  schemaItemListEnabled?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-fields".
 */
export interface FilterField {
  id: number;
  code: string;
  label: string;
  group?: (number | null) | FilterGroup;
  /**
   * The filter should reference a controlled attribute so an agent can change it safely.
   */
  attribute?: (number | null) | Attribute;
  fieldType?: ('single_select' | 'multi_select' | 'range' | 'boolean') | null;
  categories?: (number | Category)[] | null;
  isActive?: boolean | null;
  showCounters?: boolean | null;
  recalculateCounters?: boolean | null;
  allowMultiple?: boolean | null;
  indexableAllowed?: boolean | null;
  zeroResultsBehavior?: ('disable' | 'hide' | 'show') | null;
  sortOrder?: number | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups".
 */
export interface FilterGroup {
  id: number;
  code: string;
  label: string;
  isActive?: boolean | null;
  sortOrder?: number | null;
  categories?: (number | Category)[] | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  code: string;
  label: string;
  group?: (number | null) | AttributeGroup;
  valueType?: ('option' | 'multi_option' | 'number' | 'boolean' | 'text') | null;
  unit?: string | null;
  isFilterable?: boolean | null;
  isComparable?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups".
 */
export interface AttributeGroup {
  id: number;
  code: string;
  label: string;
  description?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-options".
 */
export interface AttributeOption {
  id: number;
  code: string;
  label: string;
  attribute: number | Attribute;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  indexableAllowed?: boolean | null;
  seoSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  externalUrl?: string | null;
  alt?: string | null;
  caption?: string | null;
  role?: ('product_primary' | 'product_gallery' | 'diagram' | 'drawing' | 'hero' | 'article') | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  source?: string | null;
  sortOrder?: number | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  externalUrl?: string | null;
  documentType?:
    | (
        | 'passport'
        | 'manual'
        | 'drawing'
        | 'diagram'
        | 'certificate'
        | 'declaration'
        | 'registry'
        | 'datasheet'
        | 'other'
      )
    | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  versionLabel?: string | null;
  proofRole?: string | null;
  downloadCtaLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer carts. After 30 days idle → expired, 90 days later → hard delete (GDPR).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  /**
   * URL-safe 128-bit random; HTTP-only cookie on client.
   */
  cartToken: string;
  /**
   * Linked email from checkout (if provided).
   */
  customerEmail?: string | null;
  /**
   * Forward-ref for 054 (Customer Account). Placeholder until 054 ships.
   */
  customerId?: string | null;
  /**
   * Nullable. Forward-ref for 054 (FR-5404).
   */
  companyId?: string | null;
  /**
   * GDPR/Russian PD law consent. Sources: checkout S04 checkbox OR restore-page banner.
   */
  marketingOptIn?: boolean | null;
  items?:
    | {
        sku: string;
        name: string;
        qty: number;
        /**
         * Snapshot of price at add time; null for RFQ-only.
         */
        priceAtAdd?: number | null;
        addedAt: string;
        productId?: (number | null) | Product;
        slug?: string | null;
        image?: string | null;
        /**
         * Set on GET if catalog has changed. FR-5232.
         */
        warning?: ('none' | 'removed' | 'price_changed' | 'stock_low') | null;
        id?: string | null;
      }[]
    | null;
  totals?: {
    itemCount?: number | null;
    subtotal?: number | null;
    knownPriceCount?: number | null;
    unknownPriceCount?: number | null;
  };
  status: 'active' | 'abandoned' | 'converted' | 'expired' | 'merged';
  /**
   * Set when status=converted.
   */
  convertedToOrderId?: (number | null) | Order;
  /**
   * US6 (054): merge target.
   */
  mergedIntoId?: (number | null) | Cart;
  lastActivityAt: string;
  abandonedAt?: string | null;
  convertedAt?: string | null;
  /**
   * Computed as lastActivityAt + 30d.
   */
  expiresAt: string;
  /**
   * Pathname of first add_to_cart.
   */
  sourcePage?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  /**
   * Masked UA of first add.
   */
  userAgent?: string | null;
  /**
   * SHA-256 of IP — GDPR-friendly.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-requests".
 */
export interface RfqRequest {
  id: number;
  status: 'new' | 'in_progress' | 'needs_clarification' | 'quote_preparing' | 'quoted' | 'won' | 'lost' | 'spam';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  assignedManager?: (number | null) | User;
  sourcePage?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  customerType?: ('company' | 'person' | 'integrator') | null;
  companyName?: string | null;
  inn?: string | null;
  contactName: string;
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  deadline?: string | null;
  /**
   * Legacy JSON with SKU, name, and quantity from the form.
   */
  items?: string | null;
  requestedItems?:
    | {
        sku?: string | null;
        name?: string | null;
        quantity?: string | null;
        product?: (number | null) | Product;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  technicalSpec?: string | null;
  /**
   * JSON with request source and technical metadata.
   */
  analytics?: string | null;
  internalComment?: string | null;
  nextActionAt?: string | null;
  quoteSentAt?: string | null;
  quoteNumber?: string | null;
  expectedBudget?: number | null;
  decisionStatus?: ('unknown' | 'evaluating' | 'waiting_quote' | 'approval' | 'won' | 'lost') | null;
  closeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options".
 */
export interface FilterOption {
  id: number;
  code: string;
  label: string;
  field: number | FilterField;
  attributeOption?: (number | null) | AttributeOption;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  seoSlug?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  indexableAllowed?: boolean | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-presets".
 */
export interface FilterPreset {
  id: number;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  slug: string;
  category: number | Category;
  h1?: string | null;
  intro?: string | null;
  conditions?:
    | {
        field: number | FilterField;
        options?: (number | FilterOption)[] | null;
        id?: string | null;
      }[]
    | null;
  relatedLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  indexingPolicy?: ('index' | 'noindex' | 'canonical_only') | null;
  targetQueries?:
    | {
        query: string;
        intent?: ('commercial' | 'technical' | 'informational' | 'navigational') | null;
        id?: string | null;
      }[]
    | null;
  agentEditable?: boolean | null;
  agentLockReason?: string | null;
  requiresHumanApproval?: boolean | null;
  sourceOfTruth?: ('payload' | 'source_json' | 'moysklad' | 'manual_approved') | null;
  /**
   * Data, SEO, schema.org, or public rendering validation errors.
   */
  validationErrors?: string | null;
  /**
   * Path for checking the result on the public site or preview.
   */
  previewPath?: string | null;
  revisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-change-log".
 */
export interface AdminChangeLog {
  id: number;
  actorType: 'user' | 'agent' | 'script' | 'integration';
  actorName?: string | null;
  targetCollection: string;
  targetId?: string | null;
  targetLabel: string;
  changeType: 'create' | 'update' | 'publish' | 'archive' | 'import';
  beforeSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  diffSummary?: string | null;
  reason?: string | null;
  approvalStatus?: ('not_required' | 'pending' | 'approved' | 'rejected') | null;
  approvedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-calculations".
 */
export interface ShippingCalculation {
  id: number;
  /**
   * apiship:calc:{cartId}:{shippingOptionId}
   */
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-logs".
 */
export interface ShippingLog {
  id: number;
  direction: 'out' | 'in';
  endpoint: string;
  method?: string | null;
  status?: number | null;
  requestId?: string | null;
  orderId?: string | null;
  durationMs?: number | null;
  request?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  response?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-sync-jobs".
 */
export interface CrmSyncJob {
  id: number;
  jobId: string;
  orderId: string;
  event: string;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempt?: number | null;
  status: 'queued' | 'in_progress' | 'success' | 'failed' | 'quarantined';
  lastAttemptAt?: string | null;
  nextAttemptAt?: string | null;
  errorMessage?: string | null;
  errorCode?: string | null;
  twentyRef?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-jobs".
 */
export interface NotificationJob {
  id: number;
  notificationId: string;
  orderId: number | Order;
  event: string;
  channel: 'email' | 'messenger' | 'admin_ui' | 'dataLayer';
  template: string;
  recipient: string;
  scheduledAt: string;
  sentAt?: string | null;
  status: 'queued' | 'in_progress' | 'sent' | 'failed' | 'skipped';
  attempt?: number | null;
  nextAttemptAt?: string | null;
  errorMessage?: string | null;
  errorCode?: string | null;
  externalRef?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * opt_out | duplicate | invalid_recipient | no_sender_registered | sandbox | disabled
   */
  skipReason?: string | null;
  dedupKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'rfq-requests';
        value: number | RfqRequest;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'attribute-groups';
        value: number | AttributeGroup;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'attribute-options';
        value: number | AttributeOption;
      } | null)
    | ({
        relationTo: 'filter-groups';
        value: number | FilterGroup;
      } | null)
    | ({
        relationTo: 'filter-fields';
        value: number | FilterField;
      } | null)
    | ({
        relationTo: 'filter-options';
        value: number | FilterOption;
      } | null)
    | ({
        relationTo: 'filter-presets';
        value: number | FilterPreset;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'admin-change-log';
        value: number | AdminChangeLog;
      } | null)
    | ({
        relationTo: 'shipping-calculations';
        value: number | ShippingCalculation;
      } | null)
    | ({
        relationTo: 'shipping-logs';
        value: number | ShippingLog;
      } | null)
    | ({
        relationTo: 'crm-sync-jobs';
        value: number | CrmSyncJob;
      } | null)
    | ({
        relationTo: 'notification-jobs';
        value: number | NotificationJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  customerLabel?: T;
  items?:
    | T
    | {
        sku?: T;
        name?: T;
        slug?: T;
        quantity?: T;
        price?: T;
        lineTotal?: T;
        product?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        subtotal?: T;
        vat?: T;
        deliveryCost?: T;
        total?: T;
      };
  customer?:
    | T
    | {
        fullName?: T;
        email?: T;
        phone?: T;
        companyName?: T;
        inn?: T;
        kpp?: T;
        ogrn?: T;
        legalAddress?: T;
        emailValid?: T;
      };
  delivery?:
    | T
    | {
        method?: T;
        address?: T;
        city?: T;
        cost?: T;
        trackNumber?: T;
        shippedAt?: T;
        provider?: T;
        providerKey?: T;
        tariffId?: T;
        deliveryType?: T;
        pickupType?: T;
        pointId?: T;
        pointAddress?: T;
        etaMinDays?: T;
        etaMaxDays?: T;
        selectedAt?: T;
        addressNormalized?: T;
        priceSnapshot?:
          | T
          | {
              cost?: T;
              currency?: T;
              capturedAt?: T;
              sourceCacheKey?: T;
              refreshCheckAt?: T;
            };
        pickupExpiresAt?: T;
      };
  shipment?:
    | T
    | {
        providerOrderId?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        labelUrl?: T;
        waybillUrl?: T;
        status?: T;
        events?:
          | T
          | {
              eventId?: T;
              providerStatus?: T;
              internalStatus?: T;
              at?: T;
              receivedAt?: T;
              message?: T;
              raw?: T;
              id?: T;
            };
        createdAt?: T;
        cancelledAt?: T;
        errorMessage?: T;
        lastSyncedAt?: T;
      };
  crmRefs?:
    | T
    | {
        opportunityId?: T;
        personId?: T;
        companyId?: T;
        lastSyncedAt?: T;
        lastSyncStatus?: T;
        lastSyncError?: T;
        pendingCancellationFromCrm?: T;
      };
  deliveredAt?: T;
  closedAt?: T;
  disputeFlag?: T;
  paymentRetryUntil?: T;
  hasReturns?: T;
  returnsCount?: T;
  totalRefunded?: T;
  payment?:
    | T
    | {
        method?: T;
        providerStatus?: T;
        providerRef?: T;
        paidAt?: T;
        amount?: T;
        refunds?:
          | T
          | {
              providerRefundId?: T;
              returnId?: T;
              amount?: T;
              refundedAt?: T;
              providerStatus?: T;
              id?: T;
            };
      };
  invoice?:
    | T
    | {
        number?: T;
        issuedAt?: T;
        pdfUrl?: T;
        validUntil?: T;
      };
  sourcePage?: T;
  publicToken?: T;
  cartId?: T;
  clientNumber?: T;
  clientNumberReissueReason?: T;
  clientNumberHistory?:
    | T
    | {
        oldNumber?: T;
        reissuedAt?: T;
        reason?: T;
        actorEmail?: T;
        id?: T;
      };
  internalComment?: T;
  history?:
    | T
    | {
        at?: T;
        from?: T;
        to?: T;
        note?: T;
        id?: T;
      };
  marketingOptIn?: T;
  messengerOptIn?: T;
  notifications?:
    | T
    | {
        notificationId?: T;
        event?: T;
        channel?: T;
        template?: T;
        recipient?: T;
        scheduledAt?: T;
        sentAt?: T;
        status?: T;
        errorMessage?: T;
        externalRef?: T;
        skipReason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  cartToken?: T;
  customerEmail?: T;
  customerId?: T;
  companyId?: T;
  marketingOptIn?: T;
  items?:
    | T
    | {
        sku?: T;
        name?: T;
        qty?: T;
        priceAtAdd?: T;
        addedAt?: T;
        productId?: T;
        slug?: T;
        image?: T;
        warning?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        itemCount?: T;
        subtotal?: T;
        knownPriceCount?: T;
        unknownPriceCount?: T;
      };
  status?: T;
  convertedToOrderId?: T;
  mergedIntoId?: T;
  lastActivityAt?: T;
  abandonedAt?: T;
  convertedAt?: T;
  expiresAt?: T;
  sourcePage?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  userAgent?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-requests_select".
 */
export interface RfqRequestsSelect<T extends boolean = true> {
  status?: T;
  priority?: T;
  assignedManager?: T;
  sourcePage?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  customerType?: T;
  companyName?: T;
  inn?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  city?: T;
  deadline?: T;
  items?: T;
  requestedItems?:
    | T
    | {
        sku?: T;
        name?: T;
        quantity?: T;
        product?: T;
        id?: T;
      };
  message?: T;
  technicalSpec?: T;
  analytics?: T;
  internalComment?: T;
  nextActionAt?: T;
  quoteSentAt?: T;
  quoteNumber?: T;
  expectedBudget?: T;
  decisionStatus?: T;
  closeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  status?: T;
  qualityStatus?: T;
  sku?: T;
  slug?: T;
  externalId?: T;
  title?: T;
  h1?: T;
  shortDescription?: T;
  description?: T;
  productType?: T;
  primaryCategory?: T;
  categories?: T;
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
        status?: T;
      };
  availabilityStatus?: T;
  technicalAttributes?:
    | T
    | {
        attribute?: T;
        option?: T;
        valueText?: T;
        valueNumber?: T;
        confidence?: T;
        id?: T;
      };
  imageLinks?:
    | T
    | {
        role?: T;
        url?: T;
        alt?: T;
        id?: T;
      };
  media?: T;
  documents?: T;
  relatedProducts?: T;
  ctaMode?: T;
  rfqEnabled?: T;
  sourceUrl?: T;
  sourceRawTitle?: T;
  sourceRawDescription?: T;
  lastImportedAt?: T;
  schemaProductEnabled?: T;
  schemaBrand?: T;
  schemaManufacturer?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  status?: T;
  qualityStatus?: T;
  title?: T;
  slug?: T;
  categoryType?: T;
  parent?: T;
  h1?: T;
  intro?: T;
  primaryFilters?: T;
  featuredProducts?: T;
  relatedCategories?: T;
  bottomSeoText?: T;
  schemaItemListEnabled?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups_select".
 */
export interface AttributeGroupsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  description?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  group?: T;
  valueType?: T;
  unit?: T;
  isFilterable?: T;
  isComparable?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-options_select".
 */
export interface AttributeOptionsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  attribute?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sortOrder?: T;
  isActive?: T;
  indexableAllowed?: T;
  seoSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups_select".
 */
export interface FilterGroupsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  isActive?: T;
  sortOrder?: T;
  categories?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-fields_select".
 */
export interface FilterFieldsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  group?: T;
  attribute?: T;
  fieldType?: T;
  categories?: T;
  isActive?: T;
  showCounters?: T;
  recalculateCounters?: T;
  allowMultiple?: T;
  indexableAllowed?: T;
  zeroResultsBehavior?: T;
  sortOrder?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options_select".
 */
export interface FilterOptionsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  field?: T;
  attributeOption?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  seoSlug?: T;
  sortOrder?: T;
  isActive?: T;
  indexableAllowed?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-presets_select".
 */
export interface FilterPresetsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  category?: T;
  h1?: T;
  intro?: T;
  conditions?:
    | T
    | {
        field?: T;
        options?: T;
        id?: T;
      };
  relatedLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  externalUrl?: T;
  alt?: T;
  caption?: T;
  role?: T;
  products?: T;
  categories?: T;
  source?: T;
  sortOrder?: T;
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  externalUrl?: T;
  documentType?: T;
  products?: T;
  categories?: T;
  versionLabel?: T;
  proofRole?: T;
  downloadCtaLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  indexingPolicy?: T;
  targetQueries?:
    | T
    | {
        query?: T;
        intent?: T;
        id?: T;
      };
  agentEditable?: T;
  agentLockReason?: T;
  requiresHumanApproval?: T;
  sourceOfTruth?: T;
  validationErrors?: T;
  previewPath?: T;
  revisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-change-log_select".
 */
export interface AdminChangeLogSelect<T extends boolean = true> {
  actorType?: T;
  actorName?: T;
  targetCollection?: T;
  targetId?: T;
  targetLabel?: T;
  changeType?: T;
  beforeSnapshot?: T;
  afterSnapshot?: T;
  diffSummary?: T;
  reason?: T;
  approvalStatus?: T;
  approvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-calculations_select".
 */
export interface ShippingCalculationsSelect<T extends boolean = true> {
  key?: T;
  data?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-logs_select".
 */
export interface ShippingLogsSelect<T extends boolean = true> {
  direction?: T;
  endpoint?: T;
  method?: T;
  status?: T;
  requestId?: T;
  orderId?: T;
  durationMs?: T;
  request?: T;
  response?: T;
  error?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-sync-jobs_select".
 */
export interface CrmSyncJobsSelect<T extends boolean = true> {
  jobId?: T;
  orderId?: T;
  event?: T;
  payload?: T;
  attempt?: T;
  status?: T;
  lastAttemptAt?: T;
  nextAttemptAt?: T;
  errorMessage?: T;
  errorCode?: T;
  twentyRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-jobs_select".
 */
export interface NotificationJobsSelect<T extends boolean = true> {
  notificationId?: T;
  orderId?: T;
  event?: T;
  channel?: T;
  template?: T;
  recipient?: T;
  scheduledAt?: T;
  sentAt?: T;
  status?: T;
  attempt?: T;
  nextAttemptAt?: T;
  errorMessage?: T;
  errorCode?: T;
  externalRef?: T;
  payload?: T;
  skipReason?: T;
  dedupKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiship-settings".
 */
export interface ApishipSetting {
  id: number;
  enabled?: boolean | null;
  isTest?: boolean | null;
  /**
   * Server-side only. If empty — falls back to APISHIP_TOKEN env.
   */
  token?: string | null;
  /**
   * For HMAC validation of incoming webhooks.
   */
  webhookSecret?: string | null;
  sender?: {
    countryCode?: string | null;
    addressString?: string | null;
    contactName?: string | null;
    phone?: string | null;
  };
  defaults?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
    /**
     * Grams
     */
    weight?: number | null;
    deliveryCostVat?: ('-1' | '0' | '5' | '7' | '10' | '20' | '22') | null;
    isCod?: boolean | null;
  };
  disabledProviders?:
    | {
        providerKey?: string | null;
        id?: string | null;
      }[]
    | null;
  allowedDeliveryTypes?: ('doortodoor' | 'doortopoint' | 'pointtodoor' | 'pointtopoint')[] | null;
  yandexMaps?: {
    apiKey?: string | null;
    tariffPlan?: ('free' | 'basic' | 'commercial') | null;
  };
  dadata?: {
    apiKey?: string | null;
    secret?: string | null;
    tariffPlan?: ('free' | 'starter' | 'business') | null;
    cacheTtlDays?: number | null;
  };
  lifecycle?: {
    closureWindowDays?: number | null;
    paymentRetryWindowMin?: number | null;
    invoiceExpiresDays?: number | null;
    stuckThresholdHours?: {
      paid?: number | null;
      fulfilling?: number | null;
      shipped?: number | null;
      atPoint?: number | null;
    };
    priceMismatchTolerance?: {
      percent?: number | null;
      absoluteR?: number | null;
    };
  };
  connectionStatus?: {
    lastCheckedAt?: string | null;
    ok?: boolean | null;
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-settings".
 */
export interface CrmSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Self-host URL.
   */
  baseUrl: string;
  apiKey?: string | null;
  workspaceId?: string | null;
  defaultAssignee?: string | null;
  webhookSecret?: string | null;
  mapping?: {
    createCompanyForB2B?: boolean | null;
    linkPersonByEmail?: boolean | null;
    linkCompanyByTaxId?: boolean | null;
  };
  stageMap?: {
    draft?: string | null;
    pending_payment?: string | null;
    awaiting_payment?: string | null;
    paid?: string | null;
    fulfilling?: string | null;
    shipped?: string | null;
    delivered?: string | null;
    completed?: string | null;
    cancelled?: string | null;
    returned?: string | null;
    expired?: string | null;
  };
  retry?: {
    maxAttempts?: number | null;
    baseDelaySec?: number | null;
    rateLimitRpm?: number | null;
  };
  connectionStatus?: {
    lastCheckedAt?: string | null;
    ok?: boolean | null;
    message?: string | null;
    schemaCheckOk?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-settings".
 */
export interface NotificationsSetting {
  id: number;
  /**
   * If disabled — jobs are enqueued but not delivered (dry-run).
   */
  enabled?: boolean | null;
  email: {
    provider: 'postmark' | 'mailgun' | 'sendpulse';
    /**
     * Server-side only; masked in UI.
     */
    apiKey?: string | null;
    /**
     * Used only for Mailgun, e.g. mg.soliton.ru.
     */
    domain?: string | null;
    from: string;
    replyTo?: string | null;
    /**
     * Emails are not really sent — only logged.
     */
    sandbox?: boolean | null;
  };
  /**
   * Architectural placeholder for spec 050. No sender registered in 049.
   */
  messenger?: {
    /**
     * Always false in 049; flipped on after 050.
     */
    enabled?: boolean | null;
    provider?: ('telegram' | 'max' | 'vk_messages') | null;
  };
  /**
   * Recipients of T-101..T-105 admin templates.
   */
  managers?:
    | {
        email: string;
        name?: string | null;
        events?:
          | (
              | 'order.paid'
              | 'order.invoice_issued'
              | 'shipment.error'
              | 'order.stuck'
              | 'order.cancelled'
              | 'everything'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  marketing?: {
    cartAbandonmentEnabled?: boolean | null;
    cartAbandonmentDelayMin?: number | null;
    npsEnabled?: boolean | null;
  };
  retry?: {
    maxAttempts?: number | null;
    baseDelaySec?: number | null;
    stuckQueueThreshold?: number | null;
  };
  connectionStatus?: {
    lastCheckedAt?: string | null;
    emailOk?: boolean | null;
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiship-settings_select".
 */
export interface ApishipSettingsSelect<T extends boolean = true> {
  enabled?: T;
  isTest?: T;
  token?: T;
  webhookSecret?: T;
  sender?:
    | T
    | {
        countryCode?: T;
        addressString?: T;
        contactName?: T;
        phone?: T;
      };
  defaults?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
        weight?: T;
        deliveryCostVat?: T;
        isCod?: T;
      };
  disabledProviders?:
    | T
    | {
        providerKey?: T;
        id?: T;
      };
  allowedDeliveryTypes?: T;
  yandexMaps?:
    | T
    | {
        apiKey?: T;
        tariffPlan?: T;
      };
  dadata?:
    | T
    | {
        apiKey?: T;
        secret?: T;
        tariffPlan?: T;
        cacheTtlDays?: T;
      };
  lifecycle?:
    | T
    | {
        closureWindowDays?: T;
        paymentRetryWindowMin?: T;
        invoiceExpiresDays?: T;
        stuckThresholdHours?:
          | T
          | {
              paid?: T;
              fulfilling?: T;
              shipped?: T;
              atPoint?: T;
            };
        priceMismatchTolerance?:
          | T
          | {
              percent?: T;
              absoluteR?: T;
            };
      };
  connectionStatus?:
    | T
    | {
        lastCheckedAt?: T;
        ok?: T;
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-settings_select".
 */
export interface CrmSettingsSelect<T extends boolean = true> {
  enabled?: T;
  baseUrl?: T;
  apiKey?: T;
  workspaceId?: T;
  defaultAssignee?: T;
  webhookSecret?: T;
  mapping?:
    | T
    | {
        createCompanyForB2B?: T;
        linkPersonByEmail?: T;
        linkCompanyByTaxId?: T;
      };
  stageMap?:
    | T
    | {
        draft?: T;
        pending_payment?: T;
        awaiting_payment?: T;
        paid?: T;
        fulfilling?: T;
        shipped?: T;
        delivered?: T;
        completed?: T;
        cancelled?: T;
        returned?: T;
        expired?: T;
      };
  retry?:
    | T
    | {
        maxAttempts?: T;
        baseDelaySec?: T;
        rateLimitRpm?: T;
      };
  connectionStatus?:
    | T
    | {
        lastCheckedAt?: T;
        ok?: T;
        message?: T;
        schemaCheckOk?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-settings_select".
 */
export interface NotificationsSettingsSelect<T extends boolean = true> {
  enabled?: T;
  email?:
    | T
    | {
        provider?: T;
        apiKey?: T;
        domain?: T;
        from?: T;
        replyTo?: T;
        sandbox?: T;
      };
  messenger?:
    | T
    | {
        enabled?: T;
        provider?: T;
      };
  managers?:
    | T
    | {
        email?: T;
        name?: T;
        events?: T;
        id?: T;
      };
  marketing?:
    | T
    | {
        cartAbandonmentEnabled?: T;
        cartAbandonmentDelayMin?: T;
        npsEnabled?: T;
      };
  retry?:
    | T
    | {
        maxAttempts?: T;
        baseDelaySec?: T;
        stuckQueueThreshold?: T;
      };
  connectionStatus?:
    | T
    | {
        lastCheckedAt?: T;
        emailOk?: T;
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}